// File: top.v
// Generated by MyHDL 0.10
// Date: Sun Sep 30 14:09:11 2018


`timescale 1ns/10ps

module top (
    clk100MHz,
    sdram_clk,
    sdram_return_clk,
    pb,
    topsdcntl_SdramCntl0_sd_intf_cke,
    topsdcntl_SdramCntl0_sd_intf_we,
    topsdcntl_SdramCntl0_sd_intf_addr,
    topsdcntl_SdramCntl0_sd_intf_dqml,
    topsdcntl_SdramCntl0_sd_intf_cas,
    topsdcntl_SdramCntl0_sd_intf_dqmh,
    topsdcntl_SdramCntl0_sd_intf_ras,
    topsdcntl_SdramCntl0_sd_intf_bs,
    topsdcntl_SdramCntl0_sd_intf_cs,
    topsdcntl_SdramCntl0_sd_intf_dq
);


input clk100MHz;
output sdram_clk;
wire sdram_clk;
input sdram_return_clk;
input pb;
output topsdcntl_SdramCntl0_sd_intf_cke;
reg topsdcntl_SdramCntl0_sd_intf_cke;
output topsdcntl_SdramCntl0_sd_intf_we;
reg topsdcntl_SdramCntl0_sd_intf_we;
output [12:0] topsdcntl_SdramCntl0_sd_intf_addr;
reg [12:0] topsdcntl_SdramCntl0_sd_intf_addr;
output topsdcntl_SdramCntl0_sd_intf_dqml;
reg topsdcntl_SdramCntl0_sd_intf_dqml;
output topsdcntl_SdramCntl0_sd_intf_cas;
reg topsdcntl_SdramCntl0_sd_intf_cas;
output topsdcntl_SdramCntl0_sd_intf_dqmh;
reg topsdcntl_SdramCntl0_sd_intf_dqmh;
output topsdcntl_SdramCntl0_sd_intf_ras;
reg topsdcntl_SdramCntl0_sd_intf_ras;
output [1:0] topsdcntl_SdramCntl0_sd_intf_bs;
reg [1:0] topsdcntl_SdramCntl0_sd_intf_bs;
output topsdcntl_SdramCntl0_sd_intf_cs;
reg topsdcntl_SdramCntl0_sd_intf_cs;
inout [15:0] topsdcntl_SdramCntl0_sd_intf_dq;
wire [15:0] topsdcntl_SdramCntl0_sd_intf_dq;

wire [31:0] i_wb_addr;
reg clk50MHz;
wire i_wb_we;
wire i_wb_stb;
wire i_wb_cyc;
wire [3:0] i_wb_sel;
reg o_wb_ack;
reg o_wb_stall;
wire [15:0] o_wb_data;
wire [15:0] i_wb_data;
reg topsdcntl_pb_prev;
reg topsdcntl_pb_debounced;
reg topsdcntl_initialized;
reg [5:0] topsdcntl_debounce_cntr;
wire topsdcntl_clk;
wire topsdcntl_reset;
reg [2:0] topsdcntl_SdramCntl0_cmd_r;
reg [12:0] topsdcntl_SdramCntl0_sAddr_x;
reg [2:0] topsdcntl_SdramCntl0_cmd_x;
reg [1:0] topsdcntl_SdramCntl0_activeBank_r;
reg [12:0] topsdcntl_SdramCntl0_sAddr_r;
reg [15:0] topsdcntl_SdramCntl0_sdramData_x;
reg topsdcntl_SdramCntl0_activateInProgress_s;
wire topsdcntl_SdramCntl0_host_intf_done_o;
reg topsdcntl_SdramCntl0_sDataDir_x;
reg topsdcntl_SdramCntl0_sDataDir_r;
wire [1:0] topsdcntl_SdramCntl0_ba_x;
reg [4:0] topsdcntl_SdramCntl0_rdPipeline_r;
wire [12:0] topsdcntl_SdramCntl0_row_s;
reg [13:0] topsdcntl_SdramCntl0_rfshCntr_x;
reg [1:0] topsdcntl_SdramCntl0_ba_r;
reg [4:0] topsdcntl_SdramCntl0_rdPipeline_x;
wire [15:0] topsdcntl_SdramCntl0_host_intf_data_o;
reg [13:0] topsdcntl_SdramCntl0_rfshCntr_r;
reg [15:0] topsdcntl_SdramCntl0_sDriver;
reg [1:0] topsdcntl_SdramCntl0_activeBank_x;
wire topsdcntl_SdramCntl0_host_intf_wr_i;
reg topsdcntl_SdramCntl0_doActivate_s;
wire [15:0] topsdcntl_SdramCntl0_host_intf_data_i;
wire [1:0] topsdcntl_SdramCntl0_bank_s;
reg [8:0] topsdcntl_SdramCntl0_refTimer_r;
reg topsdcntl_SdramCntl0_rdInProgress_s;
reg [8:0] topsdcntl_SdramCntl0_refTimer_x;
reg topsdcntl_SdramCntl0_writeInProgress_s;
reg [2:0] topsdcntl_SdramCntl0_state_x;
reg [15:0] topsdcntl_SdramCntl0_sData_r;
wire [8:0] topsdcntl_SdramCntl0_col_s;
reg [2:0] topsdcntl_SdramCntl0_state_r;
wire [15:0] topsdcntl_SdramCntl0_sData_x;
reg [9:0] topsdcntl_SdramCntl0_timer_x;
reg [4:0] topsdcntl_SdramCntl0_wrPipeline_x;
reg [1:0] topsdcntl_SdramCntl0_wrTimer_x;
wire topsdcntl_SdramCntl0_host_intf_rdPending_o;
wire [23:0] topsdcntl_SdramCntl0_host_intf_addr_i;
reg [4:0] topsdcntl_SdramCntl0_wrPipeline_r;
reg [15:0] topsdcntl_SdramCntl0_sdramData_r;
reg [1:0] topsdcntl_SdramCntl0_wrTimer_r;
reg [9:0] topsdcntl_SdramCntl0_timer_r;
wire topsdcntl_SdramCntl0_host_intf_rd_i;
reg [1:0] topsdcntl_SdramCntl0_rasTimer_x;
reg [1:0] topsdcntl_SdramCntl0_rasTimer_r;
reg topsdcntl_sdramdevfsm0_rand_load;
reg topsdcntl_sdramdevfsm0_rand_enable;
reg topsdcntl_sdramdevfsm0_rd_enable;
wire [15:0] topsdcntl_sdramdevfsm0_rand_val;
reg [1:0] topsdcntl_sdramdevfsm0_test_state;
reg [26:0] topsdcntl_sdramdevfsm0_address;
wire topsdcntl_sdramdevfsm0_host_intf_rst_i;
reg topsdcntl_sdramdevfsm0_wr_enable;
reg topsdcntl_sdramdevfsm0_error;
reg [15:0] topsdcntl_sdramdevfsm0_data_delay0_0_tmpdata1;
reg [15:0] topsdcntl_sdramdevfsm0_data_delay0_0_tmpdata;
reg [12:0] topsdcntl_SdramCntl0_activeRow_x [0:4-1];
reg [12:0] topsdcntl_SdramCntl0_activeRow_r [0:4-1];
reg topsdcntl_SdramCntl0_activeFlag_x [0:4-1];
reg topsdcntl_SdramCntl0_activeFlag_r [0:4-1];

assign i_wb_addr = 32'd0;
assign i_wb_we = 1'd0;
assign i_wb_stb = 1'd0;
assign i_wb_cyc = 1'd0;
assign i_wb_sel = 4'd0;
assign i_wb_data = 16'd0;
assign topsdcntl_SdramCntl0_sd_intf_dq = topsdcntl_SdramCntl0_sDriver;



assign topsdcntl_reset = ((!topsdcntl_initialized) || (!topsdcntl_pb_debounced));



assign sdram_clk = clk50MHz;
assign topsdcntl_clk = sdram_return_clk;


always @(posedge topsdcntl_clk) begin: TOP_TOPSDCNTL_DEBOUNCE_PB
    if ((pb != topsdcntl_pb_prev)) begin
        topsdcntl_debounce_cntr <= (49 - 1);
    end
    else begin
        if ((topsdcntl_debounce_cntr == 0)) begin
            topsdcntl_pb_debounced <= pb;
            topsdcntl_debounce_cntr <= 1;
        end
        else begin
            topsdcntl_debounce_cntr <= (topsdcntl_debounce_cntr - 1);
        end
    end
    topsdcntl_pb_prev <= pb;
end


always @(topsdcntl_SdramCntl0_activeRow_r[0], topsdcntl_SdramCntl0_activeRow_r[1], topsdcntl_SdramCntl0_activeRow_r[2], topsdcntl_SdramCntl0_activeRow_r[3], topsdcntl_SdramCntl0_row_s, topsdcntl_SdramCntl0_sAddr_r, topsdcntl_SdramCntl0_activateInProgress_s, topsdcntl_SdramCntl0_activeBank_r, topsdcntl_SdramCntl0_sDataDir_r, topsdcntl_SdramCntl0_ba_x, topsdcntl_SdramCntl0_rdPipeline_r, topsdcntl_SdramCntl0_ba_r, topsdcntl_SdramCntl0_rfshCntr_r, topsdcntl_SdramCntl0_host_intf_wr_i, topsdcntl_SdramCntl0_doActivate_s, topsdcntl_SdramCntl0_bank_s, topsdcntl_SdramCntl0_refTimer_r, topsdcntl_SdramCntl0_rdInProgress_s, topsdcntl_SdramCntl0_writeInProgress_s, topsdcntl_SdramCntl0_col_s, topsdcntl_SdramCntl0_state_r, topsdcntl_SdramCntl0_wrTimer_r, topsdcntl_SdramCntl0_timer_r, topsdcntl_SdramCntl0_host_intf_rd_i, topsdcntl_SdramCntl0_rasTimer_r, topsdcntl_SdramCntl0_activeFlag_r[0], topsdcntl_SdramCntl0_activeFlag_r[1], topsdcntl_SdramCntl0_activeFlag_r[2], topsdcntl_SdramCntl0_activeFlag_r[3]) begin: TOP_TOPSDCNTL_SDRAMCNTL0_COMB_FUNC
    integer index;
    topsdcntl_SdramCntl0_rdPipeline_x = {1'b0, topsdcntl_SdramCntl0_rdPipeline_r[(3 + 2)-1:1]};
    topsdcntl_SdramCntl0_wrPipeline_x = 5'h0;
    if ((topsdcntl_SdramCntl0_rasTimer_r != 0)) begin
        topsdcntl_SdramCntl0_rasTimer_x = (topsdcntl_SdramCntl0_rasTimer_r - 1);
    end
    else begin
        topsdcntl_SdramCntl0_rasTimer_x = topsdcntl_SdramCntl0_rasTimer_r;
    end
    if ((topsdcntl_SdramCntl0_wrTimer_r != 0)) begin
        topsdcntl_SdramCntl0_wrTimer_x = (topsdcntl_SdramCntl0_wrTimer_r - 1);
    end
    else begin
        topsdcntl_SdramCntl0_wrTimer_x = topsdcntl_SdramCntl0_wrTimer_r;
    end
    if ((topsdcntl_SdramCntl0_refTimer_r != 0)) begin
        topsdcntl_SdramCntl0_refTimer_x = (topsdcntl_SdramCntl0_refTimer_r - 1);
        topsdcntl_SdramCntl0_rfshCntr_x = topsdcntl_SdramCntl0_rfshCntr_r;
    end
    else begin
        topsdcntl_SdramCntl0_refTimer_x = 391;
        topsdcntl_SdramCntl0_rfshCntr_x = (topsdcntl_SdramCntl0_rfshCntr_r + 1);
    end
    topsdcntl_SdramCntl0_cmd_x = 7;
    topsdcntl_SdramCntl0_state_x = topsdcntl_SdramCntl0_state_r;
    topsdcntl_SdramCntl0_sAddr_x = topsdcntl_SdramCntl0_sAddr_r;
    topsdcntl_SdramCntl0_activeBank_x = topsdcntl_SdramCntl0_activeBank_r;
    topsdcntl_SdramCntl0_sDataDir_x = topsdcntl_SdramCntl0_sDataDir_r;
    for (index=0; index<(2 ** 2); index=index+1) begin
        topsdcntl_SdramCntl0_activeFlag_x[index] = topsdcntl_SdramCntl0_activeFlag_r[index];
        topsdcntl_SdramCntl0_activeRow_x[index] = topsdcntl_SdramCntl0_activeRow_r[index];
    end
    if ((topsdcntl_SdramCntl0_timer_r != 0)) begin
        topsdcntl_SdramCntl0_timer_x = (topsdcntl_SdramCntl0_timer_r - 1);
        topsdcntl_SdramCntl0_cmd_x = 7;
    end
    else begin
        topsdcntl_SdramCntl0_timer_x = topsdcntl_SdramCntl0_timer_r;
        case (topsdcntl_SdramCntl0_state_r)
            3'b000: begin
                topsdcntl_SdramCntl0_timer_x = 1000;
                topsdcntl_SdramCntl0_state_x = 3'b001;
            end
            3'b001: begin
                topsdcntl_SdramCntl0_cmd_x = 2;
                topsdcntl_SdramCntl0_timer_x = 1;
                topsdcntl_SdramCntl0_state_x = 3'b011;
                topsdcntl_SdramCntl0_sAddr_x = 512;
                topsdcntl_SdramCntl0_rfshCntr_x = 8;
            end
            3'b011: begin
                topsdcntl_SdramCntl0_cmd_x = 1;
                topsdcntl_SdramCntl0_timer_x = 4;
                topsdcntl_SdramCntl0_rfshCntr_x = (topsdcntl_SdramCntl0_rfshCntr_r - 1);
                if ((topsdcntl_SdramCntl0_rfshCntr_r == 1)) begin
                    topsdcntl_SdramCntl0_state_x = 3'b010;
                end
            end
            3'b010: begin
                topsdcntl_SdramCntl0_cmd_x = 0;
                topsdcntl_SdramCntl0_timer_x = 2;
                topsdcntl_SdramCntl0_state_x = 3'b100;
                topsdcntl_SdramCntl0_sAddr_x = 48;
            end
            3'b100: begin
                if ((topsdcntl_SdramCntl0_rfshCntr_r != 0)) begin
                    if (((topsdcntl_SdramCntl0_activateInProgress_s == 1'b0) && (topsdcntl_SdramCntl0_writeInProgress_s == 1'b0) && (topsdcntl_SdramCntl0_rdInProgress_s == 1'b0))) begin
                        topsdcntl_SdramCntl0_cmd_x = 2;
                        topsdcntl_SdramCntl0_timer_x = 1;
                        topsdcntl_SdramCntl0_state_x = 3'b110;
                        topsdcntl_SdramCntl0_sAddr_x = 512;
                        for (index=0; index<(2 ** 2); index=index+1) begin
                            topsdcntl_SdramCntl0_activeFlag_x[index] = 1'b0;
                        end
                    end
                end
                else if ((topsdcntl_SdramCntl0_host_intf_rd_i == 1'b1)) begin
                    if ((topsdcntl_SdramCntl0_ba_x == topsdcntl_SdramCntl0_ba_r)) begin
                        if ((topsdcntl_SdramCntl0_doActivate_s == 1'b1)) begin
                            if (((topsdcntl_SdramCntl0_activateInProgress_s == 1'b0) && (topsdcntl_SdramCntl0_writeInProgress_s == 1'b0) && (topsdcntl_SdramCntl0_rdInProgress_s == 1'b0))) begin
                                topsdcntl_SdramCntl0_cmd_x = 2;
                                topsdcntl_SdramCntl0_timer_x = 1;
                                topsdcntl_SdramCntl0_state_x = 3'b101;
                                topsdcntl_SdramCntl0_sAddr_x = 0;
                                topsdcntl_SdramCntl0_activeFlag_x[topsdcntl_SdramCntl0_bank_s] = 1'b0;
                            end
                        end
                        else if ((topsdcntl_SdramCntl0_rdInProgress_s == 1'b0)) begin
                            topsdcntl_SdramCntl0_cmd_x = 5;
                            topsdcntl_SdramCntl0_sDataDir_x = 1'b0;
                            topsdcntl_SdramCntl0_sAddr_x = topsdcntl_SdramCntl0_col_s;
                            topsdcntl_SdramCntl0_rdPipeline_x = {1'b1, topsdcntl_SdramCntl0_rdPipeline_r[(3 + 2)-1:1]};
                        end
                    end
                end
                else if ((topsdcntl_SdramCntl0_host_intf_wr_i == 1'b1)) begin
                    if ((topsdcntl_SdramCntl0_ba_x == topsdcntl_SdramCntl0_ba_r)) begin
                        if ((topsdcntl_SdramCntl0_doActivate_s == 1'b1)) begin
                            if (((topsdcntl_SdramCntl0_activateInProgress_s == 1'b0) && (topsdcntl_SdramCntl0_writeInProgress_s == 1'b0) && (topsdcntl_SdramCntl0_rdInProgress_s == 1'b0))) begin
                                topsdcntl_SdramCntl0_cmd_x = 2;
                                topsdcntl_SdramCntl0_timer_x = 1;
                                topsdcntl_SdramCntl0_state_x = 3'b101;
                                topsdcntl_SdramCntl0_sAddr_x = 0;
                                topsdcntl_SdramCntl0_activeFlag_x[topsdcntl_SdramCntl0_bank_s] = 1'b0;
                            end
                        end
                        else if ((topsdcntl_SdramCntl0_rdInProgress_s == 1'b0)) begin
                            topsdcntl_SdramCntl0_cmd_x = 4;
                            topsdcntl_SdramCntl0_sDataDir_x = 1'b1;
                            topsdcntl_SdramCntl0_sAddr_x = topsdcntl_SdramCntl0_col_s;
                            topsdcntl_SdramCntl0_wrPipeline_x = 5'h1;
                            topsdcntl_SdramCntl0_wrTimer_x = 2;
                        end
                    end
                end
                else begin
                    topsdcntl_SdramCntl0_cmd_x = 7;
                    topsdcntl_SdramCntl0_state_x = 3'b100;
                end
            end
            3'b101: begin
                topsdcntl_SdramCntl0_cmd_x = 3;
                topsdcntl_SdramCntl0_timer_x = 1;
                topsdcntl_SdramCntl0_state_x = 3'b100;
                topsdcntl_SdramCntl0_rasTimer_x = 3;
                topsdcntl_SdramCntl0_sAddr_x = topsdcntl_SdramCntl0_row_s;
                topsdcntl_SdramCntl0_activeBank_x = topsdcntl_SdramCntl0_bank_s;
                topsdcntl_SdramCntl0_activeRow_x[topsdcntl_SdramCntl0_bank_s] = topsdcntl_SdramCntl0_row_s;
                topsdcntl_SdramCntl0_activeFlag_x[topsdcntl_SdramCntl0_bank_s] = 1'b1;
            end
            3'b110: begin
                topsdcntl_SdramCntl0_cmd_x = 1;
                topsdcntl_SdramCntl0_timer_x = 4;
                topsdcntl_SdramCntl0_state_x = 3'b100;
                topsdcntl_SdramCntl0_rfshCntr_x = (topsdcntl_SdramCntl0_rfshCntr_r - 1);
            end
            default: begin
                topsdcntl_SdramCntl0_state_x = 3'b000;
            end
        endcase
    end
end


always @(posedge topsdcntl_clk, posedge topsdcntl_sdramdevfsm0_host_intf_rst_i) begin: TOP_TOPSDCNTL_SDRAMCNTL0_SEQ_FUNC
    integer index;
    if (topsdcntl_sdramdevfsm0_host_intf_rst_i == 1) begin
        topsdcntl_SdramCntl0_cmd_r <= 7;
        topsdcntl_SdramCntl0_rdPipeline_r <= 0;
        topsdcntl_SdramCntl0_sdramData_r <= 0;
        topsdcntl_SdramCntl0_ba_r <= 0;
        topsdcntl_SdramCntl0_wrPipeline_r <= 0;
        topsdcntl_SdramCntl0_sData_r <= 0;
        topsdcntl_SdramCntl0_wrTimer_r <= 0;
        topsdcntl_SdramCntl0_rfshCntr_r <= 0;
        topsdcntl_SdramCntl0_sAddr_r <= 0;
        topsdcntl_SdramCntl0_timer_r <= 0;
        topsdcntl_SdramCntl0_activeRow_r[0] <= 0;
        topsdcntl_SdramCntl0_activeRow_r[1] <= 0;
        topsdcntl_SdramCntl0_activeRow_r[2] <= 0;
        topsdcntl_SdramCntl0_activeRow_r[3] <= 0;
        topsdcntl_SdramCntl0_activeBank_r <= 0;
        topsdcntl_SdramCntl0_refTimer_r <= 391;
        topsdcntl_SdramCntl0_state_r <= 3'b000;
        topsdcntl_SdramCntl0_rasTimer_r <= 0;
        topsdcntl_SdramCntl0_sDataDir_r <= 0;
        topsdcntl_SdramCntl0_activeFlag_r[0] <= 0;
        topsdcntl_SdramCntl0_activeFlag_r[1] <= 0;
        topsdcntl_SdramCntl0_activeFlag_r[2] <= 0;
        topsdcntl_SdramCntl0_activeFlag_r[3] <= 0;
    end
    else begin
        topsdcntl_SdramCntl0_state_r <= topsdcntl_SdramCntl0_state_x;
        topsdcntl_SdramCntl0_cmd_r <= topsdcntl_SdramCntl0_cmd_x;
        topsdcntl_SdramCntl0_sAddr_r <= topsdcntl_SdramCntl0_sAddr_x;
        topsdcntl_SdramCntl0_sData_r <= topsdcntl_SdramCntl0_sData_x;
        topsdcntl_SdramCntl0_sDataDir_r <= topsdcntl_SdramCntl0_sDataDir_x;
        topsdcntl_SdramCntl0_activeBank_r <= topsdcntl_SdramCntl0_activeBank_x;
        topsdcntl_SdramCntl0_sdramData_r <= topsdcntl_SdramCntl0_sdramData_x;
        topsdcntl_SdramCntl0_wrPipeline_r <= topsdcntl_SdramCntl0_wrPipeline_x;
        topsdcntl_SdramCntl0_rdPipeline_r <= topsdcntl_SdramCntl0_rdPipeline_x;
        topsdcntl_SdramCntl0_ba_r <= topsdcntl_SdramCntl0_ba_x;
        topsdcntl_SdramCntl0_timer_r <= topsdcntl_SdramCntl0_timer_x;
        topsdcntl_SdramCntl0_rasTimer_r <= topsdcntl_SdramCntl0_rasTimer_x;
        topsdcntl_SdramCntl0_refTimer_r <= topsdcntl_SdramCntl0_refTimer_x;
        topsdcntl_SdramCntl0_wrTimer_r <= topsdcntl_SdramCntl0_wrTimer_x;
        topsdcntl_SdramCntl0_rfshCntr_r <= topsdcntl_SdramCntl0_rfshCntr_x;
        for (index=0; index<(2 ** 2); index=index+1) begin
            topsdcntl_SdramCntl0_activeRow_r[index] <= topsdcntl_SdramCntl0_activeRow_x[index];
            topsdcntl_SdramCntl0_activeFlag_r[index] <= topsdcntl_SdramCntl0_activeFlag_x[index];
        end
    end
end


always @(topsdcntl_SdramCntl0_cmd_r, topsdcntl_SdramCntl0_sData_r, topsdcntl_SdramCntl0_sAddr_r, topsdcntl_SdramCntl0_bank_s, topsdcntl_SdramCntl0_sDataDir_r) begin: TOP_TOPSDCNTL_SDRAMCNTL0_SDRAM_PIN_MAP
    topsdcntl_SdramCntl0_sd_intf_cke = 1;
    topsdcntl_SdramCntl0_sd_intf_cs = 0;
    topsdcntl_SdramCntl0_sd_intf_ras = topsdcntl_SdramCntl0_cmd_r[2];
    topsdcntl_SdramCntl0_sd_intf_cas = topsdcntl_SdramCntl0_cmd_r[1];
    topsdcntl_SdramCntl0_sd_intf_we = topsdcntl_SdramCntl0_cmd_r[0];
    topsdcntl_SdramCntl0_sd_intf_bs = topsdcntl_SdramCntl0_bank_s;
    topsdcntl_SdramCntl0_sd_intf_addr = topsdcntl_SdramCntl0_sAddr_r;
    if ((topsdcntl_SdramCntl0_sDataDir_r == 1'b1)) begin
        topsdcntl_SdramCntl0_sDriver = topsdcntl_SdramCntl0_sData_r;
    end
    else begin
        topsdcntl_SdramCntl0_sDriver = 'bz;
    end
    topsdcntl_SdramCntl0_sd_intf_dqml = 0;
    topsdcntl_SdramCntl0_sd_intf_dqmh = 0;
end



assign topsdcntl_SdramCntl0_host_intf_done_o = (topsdcntl_SdramCntl0_rdPipeline_r[0] || topsdcntl_SdramCntl0_wrPipeline_r[0]);
assign topsdcntl_SdramCntl0_host_intf_data_o = topsdcntl_SdramCntl0_sdramData_r;
assign topsdcntl_SdramCntl0_host_intf_rdPending_o = topsdcntl_SdramCntl0_rdInProgress_s;
assign topsdcntl_SdramCntl0_sData_x = topsdcntl_SdramCntl0_host_intf_data_i;



assign topsdcntl_SdramCntl0_bank_s = topsdcntl_SdramCntl0_host_intf_addr_i[((2 + 13) + 9)-1:(13 + 9)];
assign topsdcntl_SdramCntl0_ba_x = topsdcntl_SdramCntl0_host_intf_addr_i[((2 + 13) + 9)-1:(13 + 9)];
assign topsdcntl_SdramCntl0_row_s = topsdcntl_SdramCntl0_host_intf_addr_i[(13 + 9)-1:9];
assign topsdcntl_SdramCntl0_col_s = topsdcntl_SdramCntl0_host_intf_addr_i[9-1:0];


always @(topsdcntl_SdramCntl0_activeRow_r[0], topsdcntl_SdramCntl0_activeRow_r[1], topsdcntl_SdramCntl0_activeRow_r[2], topsdcntl_SdramCntl0_activeRow_r[3], topsdcntl_SdramCntl0_rdPipeline_r, topsdcntl_SdramCntl0_bank_s, topsdcntl_SdramCntl0_sdramData_r, topsdcntl_SdramCntl0_activeBank_r, topsdcntl_SdramCntl0_wrTimer_r, topsdcntl_SdramCntl0_sd_intf_dq, topsdcntl_SdramCntl0_row_s, topsdcntl_SdramCntl0_rasTimer_r, topsdcntl_SdramCntl0_activeFlag_r[0], topsdcntl_SdramCntl0_activeFlag_r[1], topsdcntl_SdramCntl0_activeFlag_r[2], topsdcntl_SdramCntl0_activeFlag_r[3]) begin: TOP_TOPSDCNTL_SDRAMCNTL0_DO_ACTIVE
    if (((topsdcntl_SdramCntl0_bank_s != topsdcntl_SdramCntl0_activeBank_r) || (topsdcntl_SdramCntl0_row_s != topsdcntl_SdramCntl0_activeRow_r[topsdcntl_SdramCntl0_bank_s]) || (topsdcntl_SdramCntl0_activeFlag_r[topsdcntl_SdramCntl0_bank_s] == 1'b0))) begin
        topsdcntl_SdramCntl0_doActivate_s = 1'b1;
    end
    else begin
        topsdcntl_SdramCntl0_doActivate_s = 1'b0;
    end
    if ((topsdcntl_SdramCntl0_rdPipeline_r[1] == 1'b1)) begin
        topsdcntl_SdramCntl0_sdramData_x = topsdcntl_SdramCntl0_sd_intf_dq;
    end
    else begin
        topsdcntl_SdramCntl0_sdramData_x = topsdcntl_SdramCntl0_sdramData_r;
    end
    if ((topsdcntl_SdramCntl0_rasTimer_r != 0)) begin
        topsdcntl_SdramCntl0_activateInProgress_s = 1'b1;
    end
    else begin
        topsdcntl_SdramCntl0_activateInProgress_s = 1'b0;
    end
    if ((topsdcntl_SdramCntl0_wrTimer_r != 0)) begin
        topsdcntl_SdramCntl0_writeInProgress_s = 1'b1;
    end
    else begin
        topsdcntl_SdramCntl0_writeInProgress_s = 1'b0;
    end
    if ((topsdcntl_SdramCntl0_rdPipeline_r[(3 + 2)-1:1] != 0)) begin
        topsdcntl_SdramCntl0_rdInProgress_s = 1'b1;
    end
    else begin
        topsdcntl_SdramCntl0_rdInProgress_s = 1'b0;
    end
end


always @(posedge topsdcntl_clk) begin: TOP_TOPSDCNTL_INTERNAL_RESET
    if ((topsdcntl_initialized == 1'b0)) begin
        topsdcntl_initialized <= (!topsdcntl_initialized);
    end
end

// In this section data is transferred to host_intf

assign topsdcntl_sdramdevfsm0_host_intf_rst_i = topsdcntl_reset;
assign topsdcntl_SdramCntl0_host_intf_wr_i = (topsdcntl_sdramdevfsm0_wr_enable && (!topsdcntl_SdramCntl0_host_intf_done_o));
assign topsdcntl_SdramCntl0_host_intf_rd_i = (topsdcntl_sdramdevfsm0_rd_enable && (!topsdcntl_SdramCntl0_host_intf_done_o));
assign topsdcntl_SdramCntl0_host_intf_data_i = topsdcntl_sdramdevfsm0_rand_val;
assign topsdcntl_SdramCntl0_host_intf_addr_i = topsdcntl_sdramdevfsm0_address;
assign o_wb_data = topsdcntl_SdramCntl0_host_intf_data_o;


always @(posedge topsdcntl_clk) begin: TOP_TOPSDCNTL_SDRAMDEVFSM0_SDRAM_FSM
    if ((topsdcntl_reset == 1'b1)) begin
        topsdcntl_sdramdevfsm0_error <= 1'b0;
        topsdcntl_sdramdevfsm0_test_state <= 2'b01;
    end
    else if ((topsdcntl_sdramdevfsm0_test_state == 2'b01)) begin
        topsdcntl_sdramdevfsm0_rand_load <= 1;
        // Load the data_i into tmpdata
        // this is the write & read req using wb
        // i_wb_stb & i_wb_we is 1 is a write
        // i_wb_stb & i_wb_we is 0 is a read
        if (((i_wb_cyc == 1) && (i_wb_sel == 15))) begin
            o_wb_stall <= 1;
            o_wb_ack <= 0;
            // this is the write req from wb
            // i_wb_we is 1
            if ((i_wb_we == 1)) begin
                topsdcntl_sdramdevfsm0_rand_load <= 0;
                topsdcntl_sdramdevfsm0_address <= i_wb_addr;
                topsdcntl_sdramdevfsm0_rand_enable <= 1;
                // copy the the tmpdata which 
                // is the data_i to tmpdata1
            end
            else begin
                // this is the read req from wb
                topsdcntl_sdramdevfsm0_address <= i_wb_addr;
                // wait for read to be done
                if ((topsdcntl_SdramCntl0_host_intf_done_o == 0)) begin
                    topsdcntl_sdramdevfsm0_rd_enable <= 1;
                end
                else begin
                    o_wb_stall <= 0;
                    o_wb_ack <= 1;
                    topsdcntl_sdramdevfsm0_rd_enable <= 0;
                    topsdcntl_sdramdevfsm0_test_state <= 2'b10;
                end
            end
            // wait for write to be done
            if ((topsdcntl_SdramCntl0_host_intf_done_o == 0)) begin
                topsdcntl_sdramdevfsm0_wr_enable <= 1;
                o_wb_stall <= 1;
            end
            else begin
                o_wb_stall <= 0;
                o_wb_ack <= 1;
                topsdcntl_sdramdevfsm0_wr_enable <= 0;
                topsdcntl_sdramdevfsm0_rd_enable <= 0;
                topsdcntl_sdramdevfsm0_rand_enable <= 0;
                topsdcntl_sdramdevfsm0_rand_load <= 1;
                topsdcntl_sdramdevfsm0_test_state <= 2'b10;
            end
        end
    end
    else begin
        topsdcntl_sdramdevfsm0_rand_load <= 1;
        topsdcntl_sdramdevfsm0_rand_enable <= 0;
        o_wb_ack <= 0;
        topsdcntl_sdramdevfsm0_error <= 1'b0;
        if ((i_wb_stb == 1)) begin
            topsdcntl_sdramdevfsm0_test_state <= 2'b01;
        end
    end
end



assign topsdcntl_sdramdevfsm0_rand_val = topsdcntl_sdramdevfsm0_data_delay0_0_tmpdata1;


always @(posedge topsdcntl_clk) begin: TOP_TOPSDCNTL_SDRAMDEVFSM0_DATA_DELAY0_0_DELAYED
    if (topsdcntl_sdramdevfsm0_rand_load) begin
        topsdcntl_sdramdevfsm0_data_delay0_0_tmpdata <= i_wb_data;
    end
    else if (topsdcntl_sdramdevfsm0_rand_enable) begin
        topsdcntl_sdramdevfsm0_data_delay0_0_tmpdata1 <= topsdcntl_sdramdevfsm0_data_delay0_0_tmpdata;
    end
end


always @(posedge clk100MHz) begin: TOP_DIVCLKBY20_0_DIV2
    clk50MHz <= (!clk50MHz);
end

endmodule
