// File: topcat.v
// Generated by MyHDL 0.10
// Date: Tue Oct  2 12:39:01 2018


`timescale 1ns/10ps

module topcat (
    clk100MHz,
    sdram_clk,
    sdram_return_clk,
    sd_intf_cke,
    sd_intf_we,
    sd_intf_addr,
    sd_intf_dqml,
    sd_intf_cas,
    sd_intf_dqmh,
    sd_intf_ras,
    sd_intf_bs,
    sd_intf_cs,
    sd_intf_dq
);


input clk100MHz;
output sdram_clk;
wire sdram_clk;
input sdram_return_clk;
output sd_intf_cke;
reg sd_intf_cke;
output sd_intf_we;
reg sd_intf_we;
output [12:0] sd_intf_addr;
reg [12:0] sd_intf_addr;
output sd_intf_dqml;
reg sd_intf_dqml;
output sd_intf_cas;
reg sd_intf_cas;
output sd_intf_dqmh;
reg sd_intf_dqmh;
output sd_intf_ras;
reg sd_intf_ras;
output [1:0] sd_intf_bs;
reg [1:0] sd_intf_bs;
output sd_intf_cs;
reg sd_intf_cs;
inout [15:0] sd_intf_dq;
wire [15:0] sd_intf_dq;

wire [31:0] i_wb_addr;
reg clk50MHz;
wire i_wb_we;
wire i_wb_stb;
wire pb;
wire i_wb_cyc;
wire [3:0] i_wb_sel;
reg o_wb_ack;
reg o_wb_stall;
wire [15:0] o_wb_data;
wire [15:0] i_wb_data;
reg maincat0_pb_prev;
reg maincat0_pb_debounced;
reg maincat0_initialized;
reg [5:0] maincat0_debounce_cntr;
wire maincat0_clk;
wire maincat0_reset;
wire maincat0_wbfsm_host_intf_done_o;
reg maincat0_wbfsm_rand_load;
reg maincat0_wbfsm_rand_enable;
wire maincat0_wbfsm_host_intf_wr_i;
reg maincat0_wbfsm_rd_enable;
wire [15:0] maincat0_wbfsm_rand_val;
wire [15:0] maincat0_wbfsm_host_intf_data_i;
wire [15:0] maincat0_wbfsm_host_intf_data_o;
reg [1:0] maincat0_wbfsm_test_state;
reg [26:0] maincat0_wbfsm_address;
wire maincat0_wbfsm_host_intf_rst_i;
wire maincat0_wbfsm_host_intf_rd_i;
reg maincat0_wbfsm_wr_enable;
reg maincat0_wbfsm_error;
wire [23:0] maincat0_wbfsm_host_intf_addr_i;
reg [15:0] maincat0_wbfsm_data_delay0_0_tmpdata1;
reg [15:0] maincat0_wbfsm_data_delay0_0_tmpdata;
reg [2:0] maincat0_SdramCntl0_cmd_r;
reg [12:0] maincat0_SdramCntl0_sAddr_x;
reg [2:0] maincat0_SdramCntl0_cmd_x;
reg [1:0] maincat0_SdramCntl0_activeBank_r;
reg [12:0] maincat0_SdramCntl0_sAddr_r;
reg [15:0] maincat0_SdramCntl0_sdramData_x;
reg maincat0_SdramCntl0_activateInProgress_s;
reg maincat0_SdramCntl0_sDataDir_x;
reg maincat0_SdramCntl0_sDataDir_r;
wire [1:0] maincat0_SdramCntl0_ba_x;
reg [4:0] maincat0_SdramCntl0_rdPipeline_r;
wire [12:0] maincat0_SdramCntl0_row_s;
reg [13:0] maincat0_SdramCntl0_rfshCntr_x;
reg [1:0] maincat0_SdramCntl0_ba_r;
reg [4:0] maincat0_SdramCntl0_rdPipeline_x;
reg [13:0] maincat0_SdramCntl0_rfshCntr_r;
reg [15:0] maincat0_SdramCntl0_sDriver;
reg [1:0] maincat0_SdramCntl0_activeBank_x;
reg maincat0_SdramCntl0_doActivate_s;
wire [1:0] maincat0_SdramCntl0_bank_s;
reg [8:0] maincat0_SdramCntl0_refTimer_r;
reg maincat0_SdramCntl0_rdInProgress_s;
reg [8:0] maincat0_SdramCntl0_refTimer_x;
reg maincat0_SdramCntl0_writeInProgress_s;
reg [2:0] maincat0_SdramCntl0_state_x;
reg [15:0] maincat0_SdramCntl0_sData_r;
wire [8:0] maincat0_SdramCntl0_col_s;
reg [2:0] maincat0_SdramCntl0_state_r;
wire [15:0] maincat0_SdramCntl0_sData_x;
reg [9:0] maincat0_SdramCntl0_timer_x;
reg [4:0] maincat0_SdramCntl0_wrPipeline_x;
reg [1:0] maincat0_SdramCntl0_wrTimer_x;
reg [4:0] maincat0_SdramCntl0_wrPipeline_r;
reg [15:0] maincat0_SdramCntl0_sdramData_r;
reg [1:0] maincat0_SdramCntl0_wrTimer_r;
reg [9:0] maincat0_SdramCntl0_timer_r;
reg [1:0] maincat0_SdramCntl0_rasTimer_x;
reg [1:0] maincat0_SdramCntl0_rasTimer_r;
reg [12:0] maincat0_SdramCntl0_activeRow_x [0:4-1];
reg [12:0] maincat0_SdramCntl0_activeRow_r [0:4-1];
reg maincat0_SdramCntl0_activeFlag_x [0:4-1];
reg maincat0_SdramCntl0_activeFlag_r [0:4-1];

assign i_wb_addr = 32'd0;
assign i_wb_we = 1'd0;
assign i_wb_stb = 1'd0;
assign pb = 1'd1;
assign i_wb_cyc = 1'd0;
assign i_wb_sel = 4'd0;
assign i_wb_data = 16'd0;



assign maincat0_reset = ((!maincat0_initialized) || (!maincat0_pb_debounced));



assign sdram_clk = clk50MHz;
assign maincat0_clk = sdram_return_clk;


always @(posedge maincat0_clk) begin: TOPCAT_MAINCAT0_DEBOUNCE_PB
    if ((pb != maincat0_pb_prev)) begin
        maincat0_debounce_cntr <= (49 - 1);
    end
    else begin
        if ((maincat0_debounce_cntr == 0)) begin
            maincat0_pb_debounced <= pb;
            maincat0_debounce_cntr <= 1;
        end
        else begin
            maincat0_debounce_cntr <= (maincat0_debounce_cntr - 1);
        end
    end
    maincat0_pb_prev <= pb;
end


always @(posedge maincat0_clk) begin: TOPCAT_MAINCAT0_INTERNAL_RESET
    if ((maincat0_initialized == 1'b0)) begin
        maincat0_initialized <= (!maincat0_initialized);
    end
end

// In this section data is transferred to host_intf

assign maincat0_wbfsm_host_intf_rst_i = maincat0_reset;
assign maincat0_wbfsm_host_intf_wr_i = (maincat0_wbfsm_wr_enable && (!maincat0_wbfsm_host_intf_done_o));
assign maincat0_wbfsm_host_intf_rd_i = (maincat0_wbfsm_rd_enable && (!maincat0_wbfsm_host_intf_done_o));
assign maincat0_wbfsm_host_intf_data_i = maincat0_wbfsm_rand_val;
assign maincat0_wbfsm_host_intf_addr_i = maincat0_wbfsm_address;
assign o_wb_data = maincat0_wbfsm_host_intf_data_o;


always @(posedge maincat0_clk) begin: TOPCAT_MAINCAT0_WBFSM_SDRAM_FSM
    if ((maincat0_reset == 1'b1)) begin
        maincat0_wbfsm_error <= 1'b0;
        maincat0_wbfsm_test_state <= 2'b01;
    end
    else if ((maincat0_wbfsm_test_state == 2'b01)) begin
        maincat0_wbfsm_rand_load <= 1;
        // Load the data_i into tmpdata
        // this is the write & read req using wb
        // i_wb_stb & i_wb_we is 1 is a write
        // i_wb_stb & i_wb_we is 0 is a read
        if (((i_wb_cyc == 1) && (i_wb_sel == 15))) begin
            o_wb_stall <= 1;
            o_wb_ack <= 0;
            // this is the write req from wb
            // i_wb_we is 1
            if ((i_wb_we == 1)) begin
                maincat0_wbfsm_rand_load <= 0;
                maincat0_wbfsm_address <= i_wb_addr;
                maincat0_wbfsm_rand_enable <= 1;
                // copy the the tmpdata which 
                // is the data_i to tmpdata1
            end
            else begin
                // this is the read req from wb
                maincat0_wbfsm_address <= i_wb_addr;
                // wait for read to be done
                if ((maincat0_wbfsm_host_intf_done_o == 0)) begin
                    maincat0_wbfsm_rd_enable <= 1;
                end
                else begin
                    o_wb_stall <= 0;
                    o_wb_ack <= 1;
                    maincat0_wbfsm_rd_enable <= 0;
                    maincat0_wbfsm_test_state <= 2'b10;
                end
            end
            // wait for write to be done
            if ((maincat0_wbfsm_host_intf_done_o == 0)) begin
                maincat0_wbfsm_wr_enable <= 1;
                o_wb_stall <= 1;
            end
            else begin
                o_wb_stall <= 0;
                o_wb_ack <= 1;
                maincat0_wbfsm_wr_enable <= 0;
                maincat0_wbfsm_rd_enable <= 0;
                maincat0_wbfsm_rand_enable <= 0;
                maincat0_wbfsm_rand_load <= 1;
                maincat0_wbfsm_test_state <= 2'b10;
            end
        end
    end
    else begin
        maincat0_wbfsm_rand_load <= 1;
        maincat0_wbfsm_rand_enable <= 0;
        o_wb_ack <= 0;
        maincat0_wbfsm_error <= 1'b0;
        if ((i_wb_stb == 1)) begin
            maincat0_wbfsm_test_state <= 2'b01;
        end
    end
end



assign maincat0_wbfsm_rand_val = maincat0_wbfsm_data_delay0_0_tmpdata1;


always @(posedge maincat0_clk) begin: TOPCAT_MAINCAT0_WBFSM_DATA_DELAY0_0_DELAYED
    if (maincat0_wbfsm_rand_load) begin
        maincat0_wbfsm_data_delay0_0_tmpdata <= i_wb_data;
    end
    else if (maincat0_wbfsm_rand_enable) begin
        maincat0_wbfsm_data_delay0_0_tmpdata1 <= maincat0_wbfsm_data_delay0_0_tmpdata;
    end
end


always @(maincat0_SdramCntl0_activeRow_r[0], maincat0_SdramCntl0_activeRow_r[1], maincat0_SdramCntl0_activeRow_r[2], maincat0_SdramCntl0_activeRow_r[3], maincat0_SdramCntl0_row_s, maincat0_SdramCntl0_sAddr_r, maincat0_SdramCntl0_activateInProgress_s, maincat0_SdramCntl0_activeBank_r, maincat0_SdramCntl0_sDataDir_r, maincat0_SdramCntl0_ba_x, maincat0_SdramCntl0_rdPipeline_r, maincat0_SdramCntl0_ba_r, maincat0_SdramCntl0_rfshCntr_r, maincat0_wbfsm_host_intf_wr_i, maincat0_SdramCntl0_doActivate_s, maincat0_SdramCntl0_bank_s, maincat0_SdramCntl0_refTimer_r, maincat0_SdramCntl0_rdInProgress_s, maincat0_SdramCntl0_writeInProgress_s, maincat0_SdramCntl0_col_s, maincat0_SdramCntl0_state_r, maincat0_SdramCntl0_wrTimer_r, maincat0_SdramCntl0_timer_r, maincat0_wbfsm_host_intf_rd_i, maincat0_SdramCntl0_rasTimer_r, maincat0_SdramCntl0_activeFlag_r[0], maincat0_SdramCntl0_activeFlag_r[1], maincat0_SdramCntl0_activeFlag_r[2], maincat0_SdramCntl0_activeFlag_r[3]) begin: TOPCAT_MAINCAT0_SDRAMCNTL0_COMB_FUNC
    integer index;
    maincat0_SdramCntl0_rdPipeline_x = {1'b0, maincat0_SdramCntl0_rdPipeline_r[(3 + 2)-1:1]};
    maincat0_SdramCntl0_wrPipeline_x = 5'h0;
    if ((maincat0_SdramCntl0_rasTimer_r != 0)) begin
        maincat0_SdramCntl0_rasTimer_x = (maincat0_SdramCntl0_rasTimer_r - 1);
    end
    else begin
        maincat0_SdramCntl0_rasTimer_x = maincat0_SdramCntl0_rasTimer_r;
    end
    if ((maincat0_SdramCntl0_wrTimer_r != 0)) begin
        maincat0_SdramCntl0_wrTimer_x = (maincat0_SdramCntl0_wrTimer_r - 1);
    end
    else begin
        maincat0_SdramCntl0_wrTimer_x = maincat0_SdramCntl0_wrTimer_r;
    end
    if ((maincat0_SdramCntl0_refTimer_r != 0)) begin
        maincat0_SdramCntl0_refTimer_x = (maincat0_SdramCntl0_refTimer_r - 1);
        maincat0_SdramCntl0_rfshCntr_x = maincat0_SdramCntl0_rfshCntr_r;
    end
    else begin
        maincat0_SdramCntl0_refTimer_x = 391;
        maincat0_SdramCntl0_rfshCntr_x = (maincat0_SdramCntl0_rfshCntr_r + 1);
    end
    maincat0_SdramCntl0_cmd_x = 7;
    maincat0_SdramCntl0_state_x = maincat0_SdramCntl0_state_r;
    maincat0_SdramCntl0_sAddr_x = maincat0_SdramCntl0_sAddr_r;
    maincat0_SdramCntl0_activeBank_x = maincat0_SdramCntl0_activeBank_r;
    maincat0_SdramCntl0_sDataDir_x = maincat0_SdramCntl0_sDataDir_r;
    for (index=0; index<(2 ** 2); index=index+1) begin
        maincat0_SdramCntl0_activeFlag_x[index] = maincat0_SdramCntl0_activeFlag_r[index];
        maincat0_SdramCntl0_activeRow_x[index] = maincat0_SdramCntl0_activeRow_r[index];
    end
    if ((maincat0_SdramCntl0_timer_r != 0)) begin
        maincat0_SdramCntl0_timer_x = (maincat0_SdramCntl0_timer_r - 1);
        maincat0_SdramCntl0_cmd_x = 7;
    end
    else begin
        maincat0_SdramCntl0_timer_x = maincat0_SdramCntl0_timer_r;
        case (maincat0_SdramCntl0_state_r)
            3'b000: begin
                maincat0_SdramCntl0_timer_x = 1000;
                maincat0_SdramCntl0_state_x = 3'b001;
            end
            3'b001: begin
                maincat0_SdramCntl0_cmd_x = 2;
                maincat0_SdramCntl0_timer_x = 1;
                maincat0_SdramCntl0_state_x = 3'b011;
                maincat0_SdramCntl0_sAddr_x = 512;
                maincat0_SdramCntl0_rfshCntr_x = 8;
            end
            3'b011: begin
                maincat0_SdramCntl0_cmd_x = 1;
                maincat0_SdramCntl0_timer_x = 4;
                maincat0_SdramCntl0_rfshCntr_x = (maincat0_SdramCntl0_rfshCntr_r - 1);
                if ((maincat0_SdramCntl0_rfshCntr_r == 1)) begin
                    maincat0_SdramCntl0_state_x = 3'b010;
                end
            end
            3'b010: begin
                maincat0_SdramCntl0_cmd_x = 0;
                maincat0_SdramCntl0_timer_x = 2;
                maincat0_SdramCntl0_state_x = 3'b100;
                maincat0_SdramCntl0_sAddr_x = 48;
            end
            3'b100: begin
                if ((maincat0_SdramCntl0_rfshCntr_r != 0)) begin
                    if (((maincat0_SdramCntl0_activateInProgress_s == 1'b0) && (maincat0_SdramCntl0_writeInProgress_s == 1'b0) && (maincat0_SdramCntl0_rdInProgress_s == 1'b0))) begin
                        maincat0_SdramCntl0_cmd_x = 2;
                        maincat0_SdramCntl0_timer_x = 1;
                        maincat0_SdramCntl0_state_x = 3'b110;
                        maincat0_SdramCntl0_sAddr_x = 512;
                        for (index=0; index<(2 ** 2); index=index+1) begin
                            maincat0_SdramCntl0_activeFlag_x[index] = 1'b0;
                        end
                    end
                end
                else if ((maincat0_wbfsm_host_intf_rd_i == 1'b1)) begin
                    if ((maincat0_SdramCntl0_ba_x == maincat0_SdramCntl0_ba_r)) begin
                        if ((maincat0_SdramCntl0_doActivate_s == 1'b1)) begin
                            if (((maincat0_SdramCntl0_activateInProgress_s == 1'b0) && (maincat0_SdramCntl0_writeInProgress_s == 1'b0) && (maincat0_SdramCntl0_rdInProgress_s == 1'b0))) begin
                                maincat0_SdramCntl0_cmd_x = 2;
                                maincat0_SdramCntl0_timer_x = 1;
                                maincat0_SdramCntl0_state_x = 3'b101;
                                maincat0_SdramCntl0_sAddr_x = 0;
                                maincat0_SdramCntl0_activeFlag_x[maincat0_SdramCntl0_bank_s] = 1'b0;
                            end
                        end
                        else if ((maincat0_SdramCntl0_rdInProgress_s == 1'b0)) begin
                            maincat0_SdramCntl0_cmd_x = 5;
                            maincat0_SdramCntl0_sDataDir_x = 1'b0;
                            maincat0_SdramCntl0_sAddr_x = maincat0_SdramCntl0_col_s;
                            maincat0_SdramCntl0_rdPipeline_x = {1'b1, maincat0_SdramCntl0_rdPipeline_r[(3 + 2)-1:1]};
                        end
                    end
                end
                else if ((maincat0_wbfsm_host_intf_wr_i == 1'b1)) begin
                    if ((maincat0_SdramCntl0_ba_x == maincat0_SdramCntl0_ba_r)) begin
                        if ((maincat0_SdramCntl0_doActivate_s == 1'b1)) begin
                            if (((maincat0_SdramCntl0_activateInProgress_s == 1'b0) && (maincat0_SdramCntl0_writeInProgress_s == 1'b0) && (maincat0_SdramCntl0_rdInProgress_s == 1'b0))) begin
                                maincat0_SdramCntl0_cmd_x = 2;
                                maincat0_SdramCntl0_timer_x = 1;
                                maincat0_SdramCntl0_state_x = 3'b101;
                                maincat0_SdramCntl0_sAddr_x = 0;
                                maincat0_SdramCntl0_activeFlag_x[maincat0_SdramCntl0_bank_s] = 1'b0;
                            end
                        end
                        else if ((maincat0_SdramCntl0_rdInProgress_s == 1'b0)) begin
                            maincat0_SdramCntl0_cmd_x = 4;
                            maincat0_SdramCntl0_sDataDir_x = 1'b1;
                            maincat0_SdramCntl0_sAddr_x = maincat0_SdramCntl0_col_s;
                            maincat0_SdramCntl0_wrPipeline_x = 5'h1;
                            maincat0_SdramCntl0_wrTimer_x = 2;
                        end
                    end
                end
                else begin
                    maincat0_SdramCntl0_cmd_x = 7;
                    maincat0_SdramCntl0_state_x = 3'b100;
                end
            end
            3'b101: begin
                maincat0_SdramCntl0_cmd_x = 3;
                maincat0_SdramCntl0_timer_x = 1;
                maincat0_SdramCntl0_state_x = 3'b100;
                maincat0_SdramCntl0_rasTimer_x = 3;
                maincat0_SdramCntl0_sAddr_x = maincat0_SdramCntl0_row_s;
                maincat0_SdramCntl0_activeBank_x = maincat0_SdramCntl0_bank_s;
                maincat0_SdramCntl0_activeRow_x[maincat0_SdramCntl0_bank_s] = maincat0_SdramCntl0_row_s;
                maincat0_SdramCntl0_activeFlag_x[maincat0_SdramCntl0_bank_s] = 1'b1;
            end
            3'b110: begin
                maincat0_SdramCntl0_cmd_x = 1;
                maincat0_SdramCntl0_timer_x = 4;
                maincat0_SdramCntl0_state_x = 3'b100;
                maincat0_SdramCntl0_rfshCntr_x = (maincat0_SdramCntl0_rfshCntr_r - 1);
            end
            default: begin
                maincat0_SdramCntl0_state_x = 3'b000;
            end
        endcase
    end
end


always @(posedge maincat0_clk, posedge maincat0_wbfsm_host_intf_rst_i) begin: TOPCAT_MAINCAT0_SDRAMCNTL0_SEQ_FUNC
    integer index;
    if (maincat0_wbfsm_host_intf_rst_i == 1) begin
        maincat0_SdramCntl0_cmd_r <= 7;
        maincat0_SdramCntl0_rdPipeline_r <= 0;
        maincat0_SdramCntl0_sdramData_r <= 0;
        maincat0_SdramCntl0_ba_r <= 0;
        maincat0_SdramCntl0_wrPipeline_r <= 0;
        maincat0_SdramCntl0_sData_r <= 0;
        maincat0_SdramCntl0_wrTimer_r <= 0;
        maincat0_SdramCntl0_rfshCntr_r <= 0;
        maincat0_SdramCntl0_sAddr_r <= 0;
        maincat0_SdramCntl0_timer_r <= 0;
        maincat0_SdramCntl0_activeRow_r[0] <= 0;
        maincat0_SdramCntl0_activeRow_r[1] <= 0;
        maincat0_SdramCntl0_activeRow_r[2] <= 0;
        maincat0_SdramCntl0_activeRow_r[3] <= 0;
        maincat0_SdramCntl0_activeBank_r <= 0;
        maincat0_SdramCntl0_refTimer_r <= 391;
        maincat0_SdramCntl0_state_r <= 3'b000;
        maincat0_SdramCntl0_rasTimer_r <= 0;
        maincat0_SdramCntl0_sDataDir_r <= 0;
        maincat0_SdramCntl0_activeFlag_r[0] <= 0;
        maincat0_SdramCntl0_activeFlag_r[1] <= 0;
        maincat0_SdramCntl0_activeFlag_r[2] <= 0;
        maincat0_SdramCntl0_activeFlag_r[3] <= 0;
    end
    else begin
        maincat0_SdramCntl0_state_r <= maincat0_SdramCntl0_state_x;
        maincat0_SdramCntl0_cmd_r <= maincat0_SdramCntl0_cmd_x;
        maincat0_SdramCntl0_sAddr_r <= maincat0_SdramCntl0_sAddr_x;
        maincat0_SdramCntl0_sData_r <= maincat0_SdramCntl0_sData_x;
        maincat0_SdramCntl0_sDataDir_r <= maincat0_SdramCntl0_sDataDir_x;
        maincat0_SdramCntl0_activeBank_r <= maincat0_SdramCntl0_activeBank_x;
        maincat0_SdramCntl0_sdramData_r <= maincat0_SdramCntl0_sdramData_x;
        maincat0_SdramCntl0_wrPipeline_r <= maincat0_SdramCntl0_wrPipeline_x;
        maincat0_SdramCntl0_rdPipeline_r <= maincat0_SdramCntl0_rdPipeline_x;
        maincat0_SdramCntl0_ba_r <= maincat0_SdramCntl0_ba_x;
        maincat0_SdramCntl0_timer_r <= maincat0_SdramCntl0_timer_x;
        maincat0_SdramCntl0_rasTimer_r <= maincat0_SdramCntl0_rasTimer_x;
        maincat0_SdramCntl0_refTimer_r <= maincat0_SdramCntl0_refTimer_x;
        maincat0_SdramCntl0_wrTimer_r <= maincat0_SdramCntl0_wrTimer_x;
        maincat0_SdramCntl0_rfshCntr_r <= maincat0_SdramCntl0_rfshCntr_x;
        for (index=0; index<(2 ** 2); index=index+1) begin
            maincat0_SdramCntl0_activeRow_r[index] <= maincat0_SdramCntl0_activeRow_x[index];
            maincat0_SdramCntl0_activeFlag_r[index] <= maincat0_SdramCntl0_activeFlag_x[index];
        end
    end
end


always @(maincat0_SdramCntl0_cmd_r, maincat0_SdramCntl0_sData_r, maincat0_SdramCntl0_sAddr_r, maincat0_SdramCntl0_bank_s, maincat0_SdramCntl0_sDataDir_r) begin: TOPCAT_MAINCAT0_SDRAMCNTL0_SDRAM_PIN_MAP
    sd_intf_cke = 1;
    sd_intf_cs = 0;
    sd_intf_ras = maincat0_SdramCntl0_cmd_r[2];
    sd_intf_cas = maincat0_SdramCntl0_cmd_r[1];
    sd_intf_we = maincat0_SdramCntl0_cmd_r[0];
    sd_intf_bs = maincat0_SdramCntl0_bank_s;
    sd_intf_addr = maincat0_SdramCntl0_sAddr_r;
    if ((maincat0_SdramCntl0_sDataDir_r == 1'b1)) begin
        maincat0_SdramCntl0_sDriver = maincat0_SdramCntl0_sData_r;
    end
    else begin
        maincat0_SdramCntl0_sDriver = 'bz;
    end
    sd_intf_dqml = 0;
    sd_intf_dqmh = 0;
end



assign maincat0_wbfsm_host_intf_done_o = (maincat0_SdramCntl0_rdPipeline_r[0] || maincat0_SdramCntl0_wrPipeline_r[0]);
assign maincat0_wbfsm_host_intf_data_o = maincat0_SdramCntl0_sdramData_r;
assign host_intf_rdPending_o = maincat0_SdramCntl0_rdInProgress_s;
assign maincat0_SdramCntl0_sData_x = maincat0_wbfsm_host_intf_data_i;



assign maincat0_SdramCntl0_bank_s = maincat0_wbfsm_host_intf_addr_i[((2 + 13) + 9)-1:(13 + 9)];
assign maincat0_SdramCntl0_ba_x = maincat0_wbfsm_host_intf_addr_i[((2 + 13) + 9)-1:(13 + 9)];
assign maincat0_SdramCntl0_row_s = maincat0_wbfsm_host_intf_addr_i[(13 + 9)-1:9];
assign maincat0_SdramCntl0_col_s = maincat0_wbfsm_host_intf_addr_i[9-1:0];


always @(maincat0_SdramCntl0_activeRow_r[0], maincat0_SdramCntl0_activeRow_r[1], maincat0_SdramCntl0_activeRow_r[2], maincat0_SdramCntl0_activeRow_r[3], maincat0_SdramCntl0_rdPipeline_r, maincat0_SdramCntl0_bank_s, maincat0_SdramCntl0_sdramData_r, maincat0_SdramCntl0_activeBank_r, maincat0_SdramCntl0_wrTimer_r, sd_intf_dq, maincat0_SdramCntl0_row_s, maincat0_SdramCntl0_rasTimer_r, maincat0_SdramCntl0_activeFlag_r[0], maincat0_SdramCntl0_activeFlag_r[1], maincat0_SdramCntl0_activeFlag_r[2], maincat0_SdramCntl0_activeFlag_r[3]) begin: TOPCAT_MAINCAT0_SDRAMCNTL0_DO_ACTIVE
    if (((maincat0_SdramCntl0_bank_s != maincat0_SdramCntl0_activeBank_r) || (maincat0_SdramCntl0_row_s != maincat0_SdramCntl0_activeRow_r[maincat0_SdramCntl0_bank_s]) || (maincat0_SdramCntl0_activeFlag_r[maincat0_SdramCntl0_bank_s] == 1'b0))) begin
        maincat0_SdramCntl0_doActivate_s = 1'b1;
    end
    else begin
        maincat0_SdramCntl0_doActivate_s = 1'b0;
    end
    if ((maincat0_SdramCntl0_rdPipeline_r[1] == 1'b1)) begin
        maincat0_SdramCntl0_sdramData_x = sd_intf_dq;
    end
    else begin
        maincat0_SdramCntl0_sdramData_x = maincat0_SdramCntl0_sdramData_r;
    end
    if ((maincat0_SdramCntl0_rasTimer_r != 0)) begin
        maincat0_SdramCntl0_activateInProgress_s = 1'b1;
    end
    else begin
        maincat0_SdramCntl0_activateInProgress_s = 1'b0;
    end
    if ((maincat0_SdramCntl0_wrTimer_r != 0)) begin
        maincat0_SdramCntl0_writeInProgress_s = 1'b1;
    end
    else begin
        maincat0_SdramCntl0_writeInProgress_s = 1'b0;
    end
    if ((maincat0_SdramCntl0_rdPipeline_r[(3 + 2)-1:1] != 0)) begin
        maincat0_SdramCntl0_rdInProgress_s = 1'b1;
    end
    else begin
        maincat0_SdramCntl0_rdInProgress_s = 1'b0;
    end
end


always @(posedge clk100MHz) begin: TOPCAT_DIVCLKBY20_0_DIV2
    clk50MHz <= (!clk50MHz);
end

endmodule
