////////////////////////////////////////////////////////////////////////////////
//
// Filename:	./toplevel.v
//
// Project:	ICO Zip, iCE40 ZipCPU demonstration project
//
// DO NOT EDIT THIS FILE!
// Computer Generated: This file is computer generated by AUTOFPGA. DO NOT EDIT.
// DO NOT EDIT THIS FILE!
//
// CmdLine:	autofpga autofpga -o . global.txt bkram.txt buserr.txt clock50.txt pic.txt pwrcount.txt version.txt hbconsole.txt gpio.txt dlyarbiter.txt zipbones.txt sdramdev.txt
//
// Creator:	Dan Gisselquist, Ph.D.
//		Gisselquist Technology, LLC
//
////////////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2017, Gisselquist Technology, LLC
//
// This program is free software (firmware): you can redistribute it and/or
// modify it under the terms of  the GNU General Public License as published
// by the Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTIBILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  (It's in the $(ROOT)/doc directory.  Run make with no
// target there if the PDF file isn't present.)  If not, see
// <http://www.gnu.org/licenses/> for a copy.
//
// License:	GPL, v3, as defined and found on www.gnu.org,
//		http://www.gnu.org/licenses/gpl.html
//
//
////////////////////////////////////////////////////////////////////////////////
//
//
`default_nettype	none


//
// Here we declare our toplevel.v (toplevel) design module.
// All design logic must take place beneath this top level.
//
// The port declarations just copy data from the @TOP.PORTLIST
// key, or equivalently from the @MAIN.PORTLIST key if
// @TOP.PORTLIST is absent.  For those peripherals that don't need
// any top level logic, the @MAIN.PORTLIST should be sufficent,
// so the @TOP.PORTLIST key may be left undefined.
//
module	toplevel(i_clk,
    sdram_clk,
    sdram_return_clk,
    sdramdev0_Sdcntl_sd_intf_cke,
    sdramdev0_Sdcntl_sd_intf_we,
    sdramdev0_Sdcntl_sd_intf_addr,
    sdramdev0_Sdcntl_sd_intf_dqml,
    sdramdev0_Sdcntl_sd_intf_cas,
    sdramdev0_Sdcntl_sd_intf_dqmh,
    sdramdev0_Sdcntl_sd_intf_ras,
    sdramdev0_Sdcntl_sd_intf_bs,
    sdramdev0_Sdcntl_sd_intf_cs,
    sdramdev0_Sdcntl_sd_intf_dq,
		// GPIO wires
		o_ledg, o_ledr, i_btn,
		// Parallel port to wishbone / console interface
		i_pp_dir, i_pp_clk, io_pp_data, o_pp_clkfb,
		o_dbgwires);
	//
	// Declaring our input and output ports.  We listed these above,
	// now we are declaring them here.
	//
	// These declarations just copy data from the @TOP.IODECLS key,
	// or from the @MAIN.IODECL key if @TOP.IODECL is absent.  For
	// those peripherals that don't do anything at the top level,
	// the @MAIN.IODECL key should be sufficient, so the @TOP.IODECL
	// key may be left undefined.
	//
	input	wire		i_clk;
output sdram_clk;
wire sdram_clk;
input sdram_return_clk;
output sdramdev0_Sdcntl_sd_intf_cke;
reg sdramdev0_Sdcntl_sd_intf_cke;
output sdramdev0_Sdcntl_sd_intf_we;
reg sdramdev0_Sdcntl_sd_intf_we;
output [12:0] sdramdev0_Sdcntl_sd_intf_addr;
reg [12:0] sdramdev0_Sdcntl_sd_intf_addr;
output sdramdev0_Sdcntl_sd_intf_dqml;
reg sdramdev0_Sdcntl_sd_intf_dqml;
output sdramdev0_Sdcntl_sd_intf_cas;
reg sdramdev0_Sdcntl_sd_intf_cas;
output sdramdev0_Sdcntl_sd_intf_dqmh;
reg sdramdev0_Sdcntl_sd_intf_dqmh;
output sdramdev0_Sdcntl_sd_intf_ras;
reg sdramdev0_Sdcntl_sd_intf_ras;
output [1:0] sdramdev0_Sdcntl_sd_intf_bs;
reg [1:0] sdramdev0_Sdcntl_sd_intf_bs;
output sdramdev0_Sdcntl_sd_intf_cs;
reg sdramdev0_Sdcntl_sd_intf_cs;
inout [15:0] sdramdev0_Sdcntl_sd_intf_dq;
wire [15:0] sdramdev0_Sdcntl_sd_intf_dq; 

wire pb;
wire [31:0] sdramdev0_i_wb_addr;
reg sdramdev0_pb_prev;
reg sdramdev0_pb_debounced;
wire sdramdev0_i_wb_cyc;
reg sdramdev0_o_wb_stall;
reg sdramdev0_initialized;
reg [5:0] sdramdev0_debounce_cntr;
wire sdramdev0_clk;
wire sdramdev0_i_wb_stb;
wire [3:0] sdramdev0_i_wb_sel;
reg sdramdev0_o_wb_ack;
wire sdramdev0_i_wb_we;
wire [15:0] sdramdev0_i_wb_data;
wire sdramdev0_reset;
wire [15:0] sdramdev0_o_wb_data;
wire sdramdev0_sdramdevfsm0_host_intf_done_o;
reg sdramdev0_sdramdevfsm0_rand_load;
reg sdramdev0_sdramdevfsm0_rand_enable;
wire sdramdev0_sdramdevfsm0_host_intf_wr_i;
reg sdramdev0_sdramdevfsm0_rd_enable;
wire [15:0] sdramdev0_sdramdevfsm0_rand_val;
wire [15:0] sdramdev0_sdramdevfsm0_host_intf_data_i;
wire [15:0] sdramdev0_sdramdevfsm0_host_intf_data_o;
reg [1:0] sdramdev0_sdramdevfsm0_test_state;
reg [26:0] sdramdev0_sdramdevfsm0_address;
wire sdramdev0_sdramdevfsm0_host_intf_rd_i;
reg sdramdev0_sdramdevfsm0_wr_enable;
reg sdramdev0_sdramdevfsm0_error;
wire [23:0] sdramdev0_sdramdevfsm0_host_intf_addr_i;
reg [15:0] sdramdev0_sdramdevfsm0_data_delay0_0_tmpdata1;
reg [15:0] sdramdev0_sdramdevfsm0_data_delay0_0_tmpdata;
reg [2:0] sdramdev0_Sdcntl_cmd_r;
reg [12:0] sdramdev0_Sdcntl_sAddr_x;
reg [2:0] sdramdev0_Sdcntl_cmd_x;
reg [1:0] sdramdev0_Sdcntl_activeBank_r;
reg [12:0] sdramdev0_Sdcntl_sAddr_r;
reg [15:0] sdramdev0_Sdcntl_sdramData_x;
reg sdramdev0_Sdcntl_activateInProgress_s;
reg sdramdev0_Sdcntl_sDataDir_x;
reg sdramdev0_Sdcntl_sDataDir_r;
wire [1:0] sdramdev0_Sdcntl_ba_x;
reg [4:0] sdramdev0_Sdcntl_rdPipeline_r;
wire [12:0] sdramdev0_Sdcntl_row_s;
reg [13:0] sdramdev0_Sdcntl_rfshCntr_x;
reg [1:0] sdramdev0_Sdcntl_ba_r;
reg [4:0] sdramdev0_Sdcntl_rdPipeline_x;
reg [13:0] sdramdev0_Sdcntl_rfshCntr_r;
reg [15:0] sdramdev0_Sdcntl_sDriver;
reg [1:0] sdramdev0_Sdcntl_activeBank_x;
reg sdramdev0_Sdcntl_doActivate_s;
wire [1:0] sdramdev0_Sdcntl_bank_s;
reg [8:0] sdramdev0_Sdcntl_refTimer_r;
reg sdramdev0_Sdcntl_rdInProgress_s;
reg [8:0] sdramdev0_Sdcntl_refTimer_x;
reg sdramdev0_Sdcntl_writeInProgress_s;
reg [2:0] sdramdev0_Sdcntl_state_x;
reg [15:0] sdramdev0_Sdcntl_sData_r;
wire [8:0] sdramdev0_Sdcntl_col_s;
reg [2:0] sdramdev0_Sdcntl_state_r;
wire [15:0] sdramdev0_Sdcntl_sData_x;
reg [9:0] sdramdev0_Sdcntl_timer_x;
reg [4:0] sdramdev0_Sdcntl_wrPipeline_x;
reg [1:0] sdramdev0_Sdcntl_wrTimer_x;
wire sdramdev0_Sdcntl_host_intf_rdPending_o;
reg [4:0] sdramdev0_Sdcntl_wrPipeline_r;
reg [15:0] sdramdev0_Sdcntl_sdramData_r;
reg [1:0] sdramdev0_Sdcntl_wrTimer_r;
reg [9:0] sdramdev0_Sdcntl_timer_r;
reg [1:0] sdramdev0_Sdcntl_rasTimer_x;
reg [1:0] sdramdev0_Sdcntl_rasTimer_r;
reg [12:0] sdramdev0_Sdcntl_activeRow_x [0:4-1];
reg [12:0] sdramdev0_Sdcntl_activeRow_r [0:4-1];
reg sdramdev0_Sdcntl_activeFlag_x [0:4-1];
reg sdramdev0_Sdcntl_activeFlag_r [0:4-1];
	// GPIO wires
	output	wire	[1:0]	o_ledg;
	output	wire		o_ledr;
	input	wire	[1:0]	i_btn;
	// Parallel port to wishbone / console interface
	input	wire		i_pp_dir, i_pp_clk;
	inout	wire	[7:0]	io_pp_data;
	output	wire		o_pp_clkfb;
	output	wire	[7:0]	o_dbgwires;


	//
	// Declaring component data, internal wires and registers
	//
	// These declarations just copy data from the @TOP.DEFNS key
	// within the component data files.
	//
	// GPIO declarations.  The two wire busses are just virtual lists of
	// input (or output) ports.
	wire	[2 -1:0]	i_gpio;
	wire	[11-1:0]	o_gpio;
	wire		s_clk, s_reset;
	//
	//
	// Parallel port interface
	//
	//
	wire	[7:0]	i_pp_data, w_pp_data;
	wire		w_pp_dbg;



	//
	// Time to call the main module within main.v.  Remember, the purpose
	// of the main.v module is to contain all of our portable logic.
	// Things that are Xilinx (or even Altera) specific, or for that
	// matter anything that requires something other than on-off logic,
	// such as the high impedence states required by many wires, is
	// kept in this (toplevel.v) module.  Everything else goes in
	// main.v.
	//
	// We automatically place s_clk, and s_reset here.  You may need
	// to define those above.  (You did, didn't you?)  Other
	// component descriptions come from the keys @TOP.MAIN (if it
	// exists), or @MAIN.PORTLIST if it does not.
	//

	main	thedesign(s_clk, s_reset,
		// GPIO wires
		i_gpio, o_gpio,
		// External USB-UART bus control
		i_pp_clk, i_pp_dir, i_pp_data, w_pp_data, o_pp_clkfb, w_pp_dbg);


	//
	// Our final section to the toplevel is used to provide all of
	// that special logic that couldnt fit in main.  This logic is
	// given by the @TOP.INSERT tag in our data files.
	//


	assign	i_gpio = { i_btn };
	assign	o_ledr = o_gpio[0];
	assign	o_ledg = o_gpio[2:1];

	assign	s_reset = 1'b0; // This design requires local, not global resets

`ifdef	VERILATOR
	assign	s_clk = i_clk;
`else
	reg	clk_50mhz;

	initial	clk_50mhz = 1'b0;
	always @(posedge i_clk)
		clk_50mhz <= !clk_50mhz;
	SB_GB global_buffer(clk_50mhz, s_clk);
`endif


	//
	// Parallel port I/O pin control
	ppio	hbi_io(i_pp_dir, io_pp_data, w_pp_data, i_pp_data);

	assign	o_dbgwires = { i_pp_dir, i_pp_clk, o_pp_clkfb,
				w_pp_dbg, i_pp_data[3:0] };




endmodule // end of toplevel.v module definition
