// File: test_readWrite.v
// Generated by MyHDL 0.10
// Date: Mon Aug 27 08:29:20 2018


`timescale 1ns/10ps

module test_readWrite (
    sd_intf_cke,
    sd_intf_we,
    sd_intf_addr,
    sd_intf_dqml,
    sd_intf_cas,
    sd_intf_dqmh,
    sd_intf_ras,
    sd_intf_bs,
    sd_intf_cs,
    sd_intf_dq,
    host_intf_wr_i,
    host_intf_done_o,
    host_intf_rdPending_o,
    host_intf_rst_i,
    host_intf_data_i,
    host_intf_data_o,
    host_intf_rd_i,
    host_intf_addr_i
);


input sd_intf_cke;
input sd_intf_we;
input [12:0] sd_intf_addr;
input sd_intf_dqml;
input sd_intf_cas;
input sd_intf_dqmh;
input sd_intf_ras;
input [1:0] sd_intf_bs;
input sd_intf_cs;
input [15:0] sd_intf_dq;
input host_intf_wr_i;
input host_intf_done_o;
input host_intf_rdPending_o;
input host_intf_rst_i;
input [15:0] host_intf_data_i;
input [15:0] host_intf_data_o;
input host_intf_rd_i;
input [23:0] host_intf_addr_i;

wire clk_i;

assign clk_i = 1'd0;


initial begin: TEST_READWRITE_TEST
    # 140;
    @(posedge host_intf_done_o);
    # 5;
    @(posedge host_intf_done_o);
    $write("Data Value : ");
    $write(" ");
    $write("%h", host_intf_data_o);
    $write(" ");
    $write(" clk : ");
    $write(" ");
    $write("%h", $time);
    $write("\n");
end

endmodule
